import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";
const BASE_URL="https://api-demo.bybit.com", MARKET_URL="https://api.bybit.com", RECV_WINDOW="5000";
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}})}
async function hmac(secret:string,payload:string){const e=new TextEncoder(),k=await crypto.subtle.importKey("raw",e.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]),s=await crypto.subtle.sign("HMAC",k,e.encode(payload));return Array.from(new Uint8Array(s)).map(v=>v.toString(16).padStart(2,"0")).join("")}
async function bybit(path:string,method:"GET"|"POST",params:Record<string,unknown>={}){const apiKey=Deno.env.get("BYBIT_DEMO_API_KEY")?.trim(),apiSecret=Deno.env.get("BYBIT_DEMO_API_SECRET")?.trim();if(!apiKey||!apiSecret)throw new Error("missing credentials");if(Deno.env.get("BYBIT_BASE_URL")?.trim()!==BASE_URL||Deno.env.get("BYBIT_ENV")?.trim().toLowerCase()!=="demo")throw new Error("environment mismatch");const ts=Date.now().toString();let payload="",url=BASE_URL+path;if(method==="GET"){const q=new URLSearchParams();Object.entries(params).filter(([,v])=>v!==undefined&&v!==null&&v!=="").sort(([a],[b])=>a.localeCompare(b)).forEach(([k,v])=>q.set(k,String(v)));payload=q.toString();if(payload)url+=`?${payload}`}else payload=JSON.stringify(params);const sig=await hmac(apiSecret,ts+apiKey+RECV_WINDOW+payload),r=await fetch(url,{method,headers:{"X-BAPI-API-KEY":apiKey,"X-BAPI-SIGN":sig,"X-BAPI-TIMESTAMP":ts,"X-BAPI-RECV-WINDOW":RECV_WINDOW,"Content-Type":"application/json"},body:method==="POST"?payload:undefined}),t=await r.text();let d:any;try{d=JSON.parse(t)}catch{throw new Error(`invalid json ${r.status}`)}if(!r.ok||d?.retCode!==0)throw new Error(d?.retMsg||`HTTP ${r.status}`);return d.result}
function decimals(s:string){const n=s.toLowerCase();if(n.includes("e-"))return Number(n.split("e-")[1]||0);return(n.split(".")[1]||"").length}
function down(v:number,s:string){const step=Number(s),d=Math.min(18,decimals(s)),u=Math.floor((v+step*1e-9)/step);let t=(u*step).toFixed(d);return t.includes(".")?t.replace(/0+$/,"").replace(/\.$/,""):t}
function up(v:number,s:string){const step=Number(s),d=Math.min(18,decimals(s)),u=Math.ceil((v-step*1e-9)/step);let t=(u*step).toFixed(d);return t.includes(".")?t.replace(/0+$/,"").replace(/\.$/,""):t}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return json({ok:false},405);try{const supplied=req.headers.get("x-bot-cron-token")||"",client=createClient(Deno.env.get("SUPABASE_URL")||"",Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",{auth:{persistSession:false}}),{data,error}=await client.schema("private").from("bot_runtime_secrets").select("secret_value").eq("secret_name","bot_cron").single();if(error||!data?.secret_value||supplied!==data.secret_value)return json({ok:false,error:"Not found"},404);const symbol="BTCUSDT",i=await fetch(`${MARKET_URL}/v5/market/instruments-info?category=spot&symbol=${symbol}`).then(r=>r.json()),o=await fetch(`${MARKET_URL}/v5/market/orderbook?category=spot&symbol=${symbol}&limit=1`).then(r=>r.json()),item=i?.result?.list?.[0],ask=Number(o?.result?.a?.[0]?.[0]),baseStep=String(item?.lotSizeFilter?.basePrecision||item?.lotSizeFilter?.qtyStep),tick=String(item?.priceFilter?.tickSize),price=up(ask*1.003,tick),qty=down(10/Number(price),baseStep),tp=down(ask*1.05,tick),sl=down(ask*0.95,tick),link=`protect_test_${Date.now()}`.slice(0,36),request={category:"spot",symbol,side:"Buy",orderType:"Limit",qty,price,timeInForce:"IOC",isLeverage:0,orderFilter:"Order",takeProfit:tp,stopLoss:sl,tpOrderType:"Market",slOrderType:"Market",orderLinkId:link},created=await bybit("/v5/order/create","POST",request);let execs:any[]=[];for(let n=0;n<8&&!execs.length;n++){await new Promise(r=>setTimeout(r,700+n*300));execs=(await bybit("/v5/execution/list","GET",{category:"spot",orderLinkId:link,limit:50}))?.list||[]}const history=(await bybit("/v5/order/history","GET",{category:"spot",orderLinkId:link,limit:20}))?.list?.[0]||null,verified=Number(history?.takeProfit||0)>0&&Number(history?.stopLoss||0)>0,gross=execs.reduce((s,e)=>s+Number(e.execQty||0),0),baseFee=execs.filter(e=>e.feeCurrency==="BTC").reduce((s,e)=>s+Number(e.execFee||0),0),net=Math.max(0,gross-baseFee);for(const f of ["OcoOrder","BidirectionalTpslOrder","tpslOrder","StopOrder"]){try{await bybit("/v5/order/cancel-all","POST",{category:"spot",symbol,orderFilter:f})}catch{}}let exit:any=null;if(net>0){await new Promise(r=>setTimeout(r,500));const sellLink=`protect_exit_${Date.now()}`.slice(0,36),sellReq={category:"spot",symbol,side:"Sell",orderType:"Market",qty:down(net*0.999999,baseStep),marketUnit:"baseCoin",timeInForce:"IOC",isLeverage:0,orderFilter:"Order",slippageToleranceType:"Percent",slippageTolerance:"0.50",orderLinkId:sellLink};exit=await bybit("/v5/order/create","POST",sellReq)}return json({ok:true,created,filledQty:gross,netQty:net,verified,history:{orderStatus:history?.orderStatus,takeProfit:history?.takeProfit,stopLoss:history?.stopLoss,stopOrderType:history?.stopOrderType},exit})}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},400)}});
