"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient, type User } from "@supabase/supabase-js";

const supabase = createClient(
  "https://xabffbjifmnoogzcttyd.supabase.co",
  "sb_publishable_-0xlsgjpG-xwVfaUGTag4A_wvgxVWwD",
);

type Row = Record<string, unknown>;
type Tab = "סקירה" | "בורסות" | "בוטים" | "אסטרטגיות" | "סיכון" | "Runtime" | "בטיחות";
const tabs: Tab[] = ["סקירה", "בורסות", "בוטים", "אסטרטגיות", "סיכון", "Runtime", "בטיחות"];

const css = `
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#050b16}
.pv2{min-height:100vh;direction:rtl;color:#edf7ff;background:radial-gradient(circle at 15% 0%,rgba(30,199,255,.08),transparent 28rem),radial-gradient(circle at 85% 10%,rgba(56,232,171,.06),transparent 24rem),#050b16;padding:24px}
.pv2-shell{max-width:1600px;margin:auto}.pv2-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:20px}
.pv2-eye{color:#35d9ff;font-size:12px;font-weight:800;letter-spacing:.12em;margin:0 0 7px}.pv2 h1{font-size:clamp(28px,4vw,46px);margin:0;letter-spacing:-.04em}.pv2-sub{color:#8ea7bc;line-height:1.65;max-width:780px}
.actions{display:flex;gap:10px;flex-wrap:wrap}.btn,.link,.tag{border:1px solid #1b4058;background:#091929;color:#dff7ff;border-radius:11px;padding:10px 14px;font:inherit;font-size:13px;font-weight:800;text-decoration:none}.btn{cursor:pointer}.btn:disabled{opacity:.55}.tag{color:#49f1b5;border-color:rgba(73,241,181,.28)}
.status{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;border:1px solid #173049;background:#071220;border-radius:14px;padding:11px 14px;margin-bottom:16px;color:#8fa7bb;font-size:12px}.status strong{color:#fff}
.tabs{display:flex;gap:8px;overflow:auto;padding-bottom:12px}.tab{white-space:nowrap;border:1px solid #18354d;background:#081524;color:#92a9bd;border-radius:10px;padding:10px 14px;font:inherit;font-size:13px;font-weight:800;cursor:pointer}.tab.on{background:#45ddf5;color:#04131d;border-color:#45ddf5}
.grid{display:grid;gap:12px}.metrics{grid-template-columns:repeat(6,minmax(0,1fr));margin-bottom:12px}.cards{grid-template-columns:repeat(3,minmax(0,1fr))}.hero{grid-template-columns:1.35fr .65fr;margin-bottom:12px}
.panel,.metric,.card{border:1px solid #17344e;background:linear-gradient(180deg,rgba(12,30,50,.92),rgba(7,18,32,.94));border-radius:15px;box-shadow:0 14px 40px rgba(0,0,0,.18)}.panel{padding:20px}.metric{padding:14px;min-height:94px}.card{padding:16px}
.ml{font-size:12px;color:#88a2b8;margin-bottom:8px}.mv{display:block;font-size:25px;direction:ltr;text-align:right}.section{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;margin-bottom:15px}.section h2{margin:0;font-size:20px}.muted{color:#88a2b8;font-size:13px;line-height:1.55}
.safe,.warn{border-radius:12px;padding:14px;line-height:1.7}.safe{border:1px solid rgba(65,238,172,.28);background:rgba(65,238,172,.06);color:#79f2c5}.warn{border:1px solid rgba(255,173,64,.32);background:rgba(255,173,64,.07);color:#ffd18c}
.top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:13px}.top h3{margin:0;font-size:16px}.meta{font-size:12px;color:#88a2b8;margin-top:4px}
.pill{display:inline-flex;border:1px solid #244862;background:#0a1b2c;color:#a9c1d4;border-radius:999px;padding:5px 9px;font-size:11px;font-weight:800;white-space:nowrap}.pill.good{color:#52efb7;border-color:rgba(82,239,183,.28);background:rgba(82,239,183,.07)}.pill.bad{color:#ff7d91;border-color:rgba(255,125,145,.3);background:rgba(255,125,145,.07)}.pill.warn{color:#ffc76c}
.list{display:grid;gap:8px}.row{display:flex;justify-content:space-between;gap:14px;border-top:1px solid rgba(41,72,95,.5);padding-top:8px;font-size:12px}.row:first-child{border-top:0;padding-top:0}.value{direction:ltr;text-align:left;font-weight:800}
.tablewrap{overflow:auto;border:1px solid #17344e;border-radius:14px;background:#071321}.table{width:100%;border-collapse:collapse;min-width:850px}.table th,.table td{padding:12px 13px;text-align:right;border-bottom:1px solid #152c40;font-size:12px}.table th{color:#7f9bb2;background:#091827;position:sticky;top:0}.ltr{direction:ltr;text-align:left}.empty{min-height:190px;display:grid;place-items:center;text-align:center;border:1px dashed #24445c;border-radius:14px;color:#7893aa;padding:20px}.empty strong{display:block;color:#dcebf5;margin-bottom:7px}.error{border:1px solid rgba(255,114,134,.38);background:rgba(255,114,134,.08);color:#ff9aaa;border-radius:13px;padding:14px;margin-bottom:14px}.loading{min-height:60vh;display:grid;place-items:center;color:#8ca7bd}.auth{max-width:520px;margin:12vh auto 0;border:1px solid #1a3c55;background:#081624;border-radius:18px;padding:28px;text-align:center}.footer{color:#5f7c92;font-size:11px;text-align:center;padding:24px 0 10px}
@media(max-width:1180px){.metrics{grid-template-columns:repeat(3,1fr)}.cards{grid-template-columns:repeat(2,1fr)}}@media(max-width:760px){.pv2{padding:14px}.pv2-head{flex-direction:column}.hero{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}.cards{grid-template-columns:1fr}.section{flex-direction:column}}@media(max-width:430px){.metrics{grid-template-columns:1fr}.actions>*{flex:1;text-align:center}}
`;

const t=(v:unknown,f="לא זמין")=>v===null||v===undefined||v===""?f:String(v);
const n=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const yn=(v:unknown)=>v===true?"כן":"לא";
const dt=(v:unknown)=>v?new Date(String(v)).toLocaleString("he-IL",{dateStyle:"short",timeStyle:"short"}):"לא זמין";
const tone=(v:unknown)=>{const s=t(v,"").toLowerCase();if(["ready","active","healthy","connected","matched","running"].includes(s))return"good";if(["error","failed","dead_letter","live","unlocked"].includes(s))return"bad";return"warn"};
function Pill({v}:{v:unknown}){return <span className={`pill ${tone(v)}`}>{t(v)}</span>}
function Metric({label,value}:{label:string;value:unknown}){return <div className="metric"><div className="ml">{label}</div><strong className="mv">{t(value,"0")}</strong></div>}
function Empty({title,desc}:{title:string;desc:string}){return <div className="empty"><div><strong>{title}</strong><span>{desc}</span></div></div>}

export default function PlatformPage(){
 const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[active,setActive]=useState<Tab>("סקירה"),[loading,setLoading]=useState(false),[updated,setUpdated]=useState<Date|null>(null),[error,setError]=useState("");
 const [summary,setSummary]=useState<Row|null>(null),[exchanges,setExchanges]=useState<Row[]>([]),[bots,setBots]=useState<Row[]>([]),[strategies,setStrategies]=useState<Row[]>([]),[risk,setRisk]=useState<Row[]>([]),[flags,setFlags]=useState<Row[]>([]),[legacy,setLegacy]=useState<Row[]>([]),[queue,setQueue]=useState<Row[]>([]),[workers,setWorkers]=useState<Row[]>([]),[rates,setRates]=useState<Row[]>([]),[intents,setIntents]=useState<Row[]>([]);
 useEffect(()=>{let live=true;supabase.auth.getUser().then(({data})=>{if(live){setUser(data.user);setReady(true)}});const {data}=supabase.auth.onAuthStateChange((_e,s)=>{setUser(s?.user??null);setReady(true)});return()=>{live=false;data.subscription.unsubscribe()}},[]);
 const load=useCallback(async()=>{if(!user)return;setLoading(true);setError("");
  const results=await Promise.all([
   supabase.from("platform_architecture_summary").select("*").maybeSingle(),
   supabase.from("exchange_catalog").select("*").order("display_name"),
   supabase.from("bot_instances").select("*").order("created_at"),
   supabase.from("strategy_definitions").select("*").order("display_name"),
   supabase.from("risk_profiles").select("*").order("display_name"),
   supabase.from("platform_feature_flags").select("*").order("flag_key"),
   supabase.from("platform_legacy_bot_mapping").select("*").order("display_name"),
   supabase.from("platform_queue_health").select("*"),
   supabase.from("platform_worker_health").select("*"),
   supabase.from("platform_rate_limit_health").select("*"),
   supabase.from("execution_intents").select("*").order("created_at",{ascending:false}).limit(25),
  ]);
  const first=results.find(x=>x.error)?.error;if(first)setError(first.message);
  if(!results[0].error)setSummary((results[0].data as Row|null)??null);
  if(!results[1].error)setExchanges((results[1].data as Row[])??[]);
  if(!results[2].error)setBots((results[2].data as Row[])??[]);
  if(!results[3].error)setStrategies((results[3].data as Row[])??[]);
  if(!results[4].error)setRisk((results[4].data as Row[])??[]);
  if(!results[5].error)setFlags((results[5].data as Row[])??[]);
  if(!results[6].error)setLegacy((results[6].data as Row[])??[]);
  if(!results[7].error)setQueue((results[7].data as Row[])??[]);
  if(!results[8].error)setWorkers((results[8].data as Row[])??[]);
  if(!results[9].error)setRates((results[9].data as Row[])??[]);
  if(!results[10].error)setIntents((results[10].data as Row[])??[]);
  setUpdated(new Date());setLoading(false)
 },[user]);
 useEffect(()=>{if(!user)return;void load();const id=window.setInterval(()=>void load(),20000);return()=>window.clearInterval(id)},[user,load]);
 const enabled=useMemo(()=>flags.filter(x=>x.enabled===true).length,[flags]);

 if(!ready)return <main className="pv2"><style>{css}</style><div className="loading">בודק הרשאת משתמש…</div></main>;
 if(!user)return <main className="pv2"><style>{css}</style><section className="auth"><p className="pv2-eye">PLATFORM V2</p><h1>נדרשת התחברות</h1><p className="muted">היכנס דרך הדשבורד הראשי ולאחר מכן חזור ל־<span dir="ltr">/platform</span>.</p><a className="link" href="/">מעבר לדשבורד</a></section></main>;

 return <main className="pv2"><style>{css}</style><div className="pv2-shell">
  <header className="pv2-head"><div><p className="pv2-eye">CRYPTO MARKET PLATFORM — V2</p><h1>מרכז השליטה הרב־בורסאי</h1><p className="pv2-sub">Control Plane חדש לקריאה בלבד: בורסות, בוטים, אסטרטגיות, סיכון, Workers ונעילות מרכזיות מתוך Supabase.</p></div><div className="actions"><span className="tag">קריאה בלבד</span><a className="link" href="/">Trading OS הקיים</a><button className="btn" onClick={()=>void load()} disabled={loading}>{loading?"מרענן…":"רענון"}</button></div></header>
  <div className="status"><span>משתמש: <strong dir="ltr">{user.email}</strong></span><span>עדכון: <strong>{updated?updated.toLocaleTimeString("he-IL"):"טרם נטען"}</strong></span><span>ענף: <strong dir="ltr">platform-v2</strong></span></div>
  {error&&<div className="error">חלק מהנתונים לא נטענו: <span dir="ltr">{error}</span></div>}
  <nav className="tabs">{tabs.map(x=><button key={x} className={`tab ${active===x?"on":""}`} onClick={()=>setActive(x)}>{x}</button>)}</nav>

  {active==="סקירה"&&<><section className="grid hero"><div className="panel"><div className="section"><div><h2>{t(summary?.organization_name,"Workspace")}</h2><p className="muted">המערכת החדשה קיימת לצד המנועים הקיימים ואינה שולטת עדיין בביצוע.</p></div><Pill v={summary?.organization_status??"active"}/></div><div className="safe">Platform V2 אינו שולח פקודות. כל בוט חדש מושבת, Kill Switch פעיל ו־Live נעול.</div></div><div className="panel"><h2>נעילות</h2><div className="list" style={{marginTop:16}}><div className="row"><span>Live</span><strong className="value">{summary?.live_trading_enabled_by_platform_core===true?"פתוח":"נעול"}</strong></div><div className="row"><span>משיכות</span><strong className="value">{summary?.withdrawals_enabled_by_platform_core===true?"פתוח":"נעול"}</strong></div><div className="row"><span>Flags פעילים</span><strong className="value">{enabled}</strong></div></div></div></section>
   <section className="grid metrics"><Metric label="חברי צוות" value={summary?.active_members}/><Metric label="חיבורי בורסות" value={summary?.exchange_connections}/><Metric label="חשבונות" value={summary?.trading_accounts}/><Metric label="בוטים" value={summary?.bot_instances}/><Metric label="אסטרטגיות" value={summary?.strategies}/><Metric label="פרופילי סיכון" value={summary?.risk_profiles}/></section>
   <section className="panel"><div className="section"><div><h2>מיפוי מנועים קיימים</h2><p className="muted">Legacy Bots רשומים לצורכי מעבר הדרגתי בלבד.</p></div><span className="pill">{legacy.length} מנועים</span></div>{legacy.length===0?<Empty title="אין מיפוי" desc="הנתונים יופיעו לאחר רישום המנועים."/>:<div className="grid cards">{legacy.map(b=><article className="card" key={t(b.platform_bot_id)}><div className="top"><div><h3>{t(b.display_name)}</h3><div className="meta ltr">{t(b.bot_key)}</div></div><Pill v={b.execution_environment}/></div><div className="list"><div className="row"><span>Legacy</span><strong className="value">{t(b.legacy_runtime_status)}</strong></div><div className="row"><span>Platform</span><strong className="value">{t(b.platform_runtime_status)}</strong></div><div className="row"><span>Kill Switch</span><strong className="value">{yn(b.platform_kill_switch)}</strong></div><div className="row"><span>Core Controls</span><strong className="value">{t(b.platform_core_controls_execution)}</strong></div><div className="row"><span>ריצה</span><strong className="value">{dt(b.last_run_at)}</strong></div></div></article>)}</div>}</section>
  </>}

  {active==="בורסות"&&<section className="panel"><div className="section"><div><h2>קטלוג בורסות</h2><p className="muted">הקטלוג מציג יכולות מתוכננות; רק Bybit Demo פעיל במערכת הקיימת.</p></div><span className="pill">{exchanges.length} בורסות</span></div><div className="grid cards">{exchanges.map(x=><article className="card" key={t(x.exchange_key)}><div className="top"><div><h3>{t(x.display_name)}</h3><div className="meta ltr">{t(x.exchange_key)}</div></div><Pill v={x.connector_status}/></div><div className="list"><div className="row"><span>REST</span><strong className="value">{yn(x.supports_rest)}</strong></div><div className="row"><span>WebSocket</span><strong className="value">{yn(x.supports_websocket)}</strong></div><div className="row"><span>Spot</span><strong className="value">{yn(x.supports_spot)}</strong></div><div className="row"><span>Futures</span><strong className="value">{yn(x.supports_futures)}</strong></div><div className="row"><span>Demo</span><strong className="value">{yn(x.supports_demo)}</strong></div></div></article>)}</div></section>}

  {active==="בוטים"&&<section className="panel"><div className="section"><div><h2>מופעי בוטים</h2><p className="muted">ניהול רב־בוטי עם Worker Pool, Heartbeat ושער Live.</p></div><span className="pill">{bots.length}</span></div>{bots.length===0?<Empty title="אין בוטים חדשים" desc="כרגע קיימים רק מנועי Legacy ממופים."/>:<div className="tablewrap"><table className="table"><thead><tr><th>שם</th><th>סביבה</th><th>Runtime</th><th>Enabled</th><th>Kill Switch</th><th>Live Gate</th><th>Worker</th><th>Heartbeat</th></tr></thead><tbody>{bots.map(b=><tr key={t(b.id)}><td><strong>{t(b.display_name)}</strong><div className="muted ltr">{t(b.bot_key)}</div></td><td><Pill v={b.execution_environment}/></td><td>{t(b.runtime_status)}</td><td>{yn(b.enabled)}</td><td>{yn(b.kill_switch)}</td><td>{t(b.live_gate_status)}</td><td className="ltr">{t(b.worker_pool)}</td><td className="ltr">{dt(b.last_heartbeat_at)}</td></tr>)}</tbody></table></div>}</section>}

  {active==="אסטרטגיות"&&<section className="panel"><div className="section"><div><h2>קטלוג אסטרטגיות</h2><p className="muted">הגדרות וגרסאות מופרדות מהבוטים לצורך Audit וקידום מבוקר.</p></div><span className="pill">{strategies.length}</span></div>{strategies.length===0?<Empty title="טרם נרשמו אסטרטגיות" desc="אסטרטגיות Legacy ממשיכות לפעול בנפרד."/>:<div className="tablewrap"><table className="table"><thead><tr><th>שם</th><th>משפחה</th><th>שווקים</th><th>כיוונים</th><th>Lifecycle</th><th>עדכון</th></tr></thead><tbody>{strategies.map(s=><tr key={t(s.id)}><td><strong>{t(s.display_name)}</strong><div className="muted ltr">{t(s.strategy_key)}</div></td><td>{t(s.strategy_family)}</td><td className="ltr">{Array.isArray(s.supported_markets)?s.supported_markets.join(", "):"לא זמין"}</td><td className="ltr">{Array.isArray(s.supported_directions)?s.supported_directions.join(", "):"לא זמין"}</td><td><Pill v={s.lifecycle_status}/></td><td className="ltr">{dt(s.updated_at)}</td></tr>)}</tbody></table></div>}</section>}

  {active==="סיכון"&&<section className="panel"><div className="section"><div><h2>פרופילי סיכון</h2><p className="muted">כל בוט יקבל גבולות נפרדים; משיכות נשארות חסומות.</p></div><span className="pill">{risk.length}</span></div>{risk.length===0?<Empty title="אין פרופילי סיכון" desc="יוגדרו לפני Runtime חדש."/>:<div className="tablewrap"><table className="table"><thead><tr><th>פרופיל</th><th>סביבה</th><th>לפקודה</th><th>פוזיציות</th><th>חשיפה</th><th>הפסד יומי</th><th>מינוף</th><th>Native</th><th>משיכות</th></tr></thead><tbody>{risk.map(r=><tr key={t(r.id)}><td><strong>{t(r.display_name)}</strong><div className="muted ltr">{t(r.profile_key)}</div></td><td><Pill v={r.environment}/></td><td className="ltr">${n(r.max_notional_per_order).toFixed(2)}</td><td className="ltr">{n(r.max_open_positions)}</td><td className="ltr">${n(r.max_total_exposure).toFixed(2)}</td><td className="ltr">${n(r.max_daily_loss).toFixed(2)}</td><td className="ltr">{n(r.max_leverage)}×</td><td>{yn(r.require_native_protection)}</td><td><Pill v={r.allow_withdrawals===true?"unlocked":"locked"}/></td></tr>)}</tbody></table></div>}</section>}

  {active==="Runtime"&&<><section className="grid metrics"><Metric label="ממתינים" value={queue[0]?.pending_events}/><Metric label="בעיבוד" value={queue[0]?.processing_events}/><Metric label="נכשלו" value={queue[0]?.failed_events}/><Metric label="Dead Letter" value={queue[0]?.dead_letter_events}/><Metric label="Worker Pools" value={workers.length}/><Metric label="Rate Limits" value={rates.length}/></section><section className="grid hero"><div className="panel"><div className="section"><div><h2>Workers</h2><p className="muted">Runtime קבוע עדיין לא הופעל.</p></div></div>{workers.length===0?<Empty title="אין Workers פעילים" desc="זהו המצב הצפוי לפני Runtime V1."/>:<div className="grid cards">{workers.map(w=><article className="card" key={t(w.worker_pool)}><div className="top"><h3>{t(w.worker_pool)}</h3><span className="pill">{n(w.active_leases)} פעילים</span></div><div className="list"><div className="row"><span>Leases</span><strong className="value">{n(w.total_leases)}</strong></div><div className="row"><span>פגי תוקף</span><strong className="value">{n(w.expired_leases)}</strong></div><div className="row"><span>Heartbeat</span><strong className="value">{dt(w.latest_heartbeat_at)}</strong></div></div></article>)}</div>}</div><div className="panel"><h2>Execution Intents</h2><p className="muted">בקשות מנורמלות לפני שליחת פקודה.</p><div style={{marginTop:16}}>{intents.length===0?<div className="safe">אין Intents. Platform Core אינו שולח פקודות.</div>:<div className="warn">קיימים {intents.length} Intents לבדיקה.</div>}</div></div></section><section className="panel"><div className="section"><div><h2>Rate Limits</h2><p className="muted">יתמלאו לאחר חיבור Adapter פעיל.</p></div></div>{rates.length===0?<Empty title="אין נתוני Rate Limit" desc="יופיעו לאחר הפעלת Worker."/>:<div className="tablewrap"><table className="table"><thead><tr><th>בורסה</th><th>חשבון</th><th>Scope</th><th>Endpoint</th><th>נותר</th><th>מצב</th><th>עדכון</th></tr></thead><tbody>{rates.map((r,i)=><tr key={`${t(r.connection_id)}-${i}`}><td>{t(r.exchange)}</td><td>{t(r.account_label)}</td><td className="ltr">{t(r.rate_limit_scope)}</td><td className="ltr">{t(r.endpoint_group)}</td><td className="ltr">{n(r.remaining)} / {n(r.capacity)}</td><td><Pill v={r.health_status}/></td><td className="ltr">{dt(r.updated_at)}</td></tr>)}</tbody></table></div>}</section></>}

  {active==="בטיחות"&&<><section className="grid hero"><div className="panel"><div className="section"><div><h2>Feature Flags</h2><p className="muted">יכולות מסוכנות דורשות הפעלה מפורשת וביקורת.</p></div></div><div className="grid cards">{flags.map(f=><article className="card" key={t(f.flag_key)}><div className="top"><div><h3 className="ltr">{t(f.flag_key)}</h3><div className="meta">{dt(f.updated_at)}</div></div><Pill v={f.enabled===true?"active":"locked"}/></div></article>)}</div></div><div className="panel"><h2>עקרונות</h2><div className="list" style={{marginTop:16}}><div className="row"><span>Live Trading</span><strong className="value">נעול</strong></div><div className="row"><span>Withdrawals</span><strong className="value">Hard Locked</strong></div><div className="row"><span>בוט חדש</span><strong className="value">Disabled</strong></div><div className="row"><span>Kill Switch</span><strong className="value">Active</strong></div><div className="row"><span>שליחת פקודות מ־V2</span><strong className="value">לא קיימת</strong></div></div></div></section><section className="panel"><div className="warn">לפני Runtime חדש יידרשו Adapter Contract, Idempotency, Reconciliation, Rate Limits, Audit ו־Kill Switch מרכזי.</div></section></>}
  <footer className="footer">Crypto Market Platform V2 · Read-only Control Plane · Supabase</footer>
 </div></main>
}
